In [1]:
import pandas as pd
import numpy as np
import ydata_profiling as yp
import seaborn as sns
import matplotlib.pyplot as plt

/Users/angelgovea/Library/CloudStorage/OneDrive-InstitutoTecnologicoydeEstudiosSuperioresdeMonterrey/5to Semestre/Optimizacion Estocastica/globant/globant/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
data = pd.read_csv('../data/data_globant_cleaned.csv')

display(data.head())

,Date,Name,Position,Seniority,Location,Studio,Client Tag,Project Tag,Team Name,Engagement,Leader Name,Engagement Group
0,2023-01-02,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,3.04,Laura Leon,3
1,2023-01-03,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.99,Laura Leon,3
2,2023-01-04,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.97,Laura Leon,3
3,2023-01-05,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.75,Laura Leon,2
4,2023-01-06,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,3.15,Laura Leon,3

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11366 entries, 0 to 11365
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          11366 non-null  object
 1   Email         11366 non-null  object
 2   Name          11366 non-null  object
 3   Position      11366 non-null  object
 4   Seniority     11366 non-null  object
 5   Location      11366 non-null  object
 6   Studio        11366 non-null  object
 7   Client        11366 non-null  object
 8   Client Tag    11366 non-null  object
 9   Project       11366 non-null  object
 10  Project Tag   11366 non-null  object
 11  Team Name     11366 non-null  object
 12  Engagement    11366 non-null  float64
 13  Email Leader  10226 non-null  object
 14  Year          11366 non-null  int64
 15  Month         11366 non-null  int64
 16  Day           11366 non-null  int64
dtypes: float64(1), int64(3), object(13)
memory usage: 1.5+ MB

In [4]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Engagement,11366.0,2.995252,1.005442,0.0,2.52,3.05,3.6,5.0
Year,11366.0,2023.000000,0.000000,2023.0,2023.00,2023.00,2023.0,2023.0
Month,11366.0,3.540120,1.724827,1.0,2.00,4.00,5.0,6.0
Day,11366.0,15.871547,8.754934,1.0,9.00,16.00,23.0,31.0

In [5]:
data.isna().sum().sort_values(ascending=False)
data.duplicated().sum()

0

In [ ]:
profile = yp.ProfileReport(data, title="EDA_preliminar", explorative=True)
profile.to_file("../reports/EDA_preliminar.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 17/17 [00:00<00:00, 67.87it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
profile = yp.ProfileReport(data, title="EDA", explorative=True)
profile.to_file("../reports/EDA.html")

Summarize dataset: 100%|██████████| 25/25 [00:00<00:00, 46.38it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 750.19it/s]