In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../data/data_globant.csv')

In [3]:
data.head()

,Date,Email,Name,Position,Seniority,Location,Studio,Client,Client Tag,Project,Project Tag,Team Name,Engagement,Email Leader,Year,Month,Day
0,02Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.04,laura.leon@tec.globant.com,2023,1,2
1,03Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.99,laura.leon@tec.globant.com,2023,1,3
2,04Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.97,laura.leon@tec.globant.com,2023,1,4
3,05Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.75,laura.leon@tec.globant.com,2023,1,5
4,06Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.15,laura.leon@tec.globant.com,2023,1,6

### Date to timestamp

In [4]:
data['Date'] = pd.to_datetime(data['Date'], format='%d%b%y')

In [5]:
data['Date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 11366 entries, 0 to 11365
Series name: Date
Non-Null Count  Dtype
--------------  -----
11366 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 88.9 KB

### Drop columns

In [6]:
data.drop(columns = ['Email', 'Client','Project', 'Year', 'Month', 'Day'], inplace = True)

In [7]:
data.head()

,Date,Name,Position,Seniority,Location,Studio,Client Tag,Project Tag,Team Name,Engagement,Email Leader
0,2023-01-02,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,3.04,laura.leon@tec.globant.com
1,2023-01-03,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.99,laura.leon@tec.globant.com
2,2023-01-04,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.97,laura.leon@tec.globant.com
3,2023-01-05,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.75,laura.leon@tec.globant.com
4,2023-01-06,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,3.15,laura.leon@tec.globant.com

### formating email leader

In [8]:
data['Email Leader'] = data['Email Leader'].str.split('@').str[0]
data['Email Leader'] = data['Email Leader'].str.replace(r'[._]', ' ', regex=True).str.title()

In [9]:
data = data.rename(columns={'Email Leader': 'Leader Name'})

In [10]:
data.head()

,Date,Name,Position,Seniority,Location,Studio,Client Tag,Project Tag,Team Name,Engagement,Leader Name
0,2023-01-02,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,3.04,Laura Leon
1,2023-01-03,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.99,Laura Leon
2,2023-01-04,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.97,Laura Leon
3,2023-01-05,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,2.75,Laura Leon
4,2023-01-06,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GWI001,ATLINT,Breaking Badger,3.15,Laura Leon

### Name leader for managers

In [11]:
data['Leader Name'] = data['Leader Name'].fillna(data['Name'])

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11366 entries, 0 to 11365
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         11366 non-null  datetime64[ns]
 1   Name         11366 non-null  object
 2   Position     11366 non-null  object
 3   Seniority    11366 non-null  object
 4   Location     11366 non-null  object
 5   Studio       11366 non-null  object
 6   Client Tag   11366 non-null  object
 7   Project Tag  11366 non-null  object
 8   Team Name    11366 non-null  object
 9   Engagement   11366 non-null  float64
 10  Leader Name  11366 non-null  object
dtypes: datetime64[ns](1), float64(1), object(9)
memory usage: 976.9+ KB

### exportar csv

In [13]:
data.to_csv('../data/data_globant_cleaned.csv', index=False)